Add sytem wide theming
cyberjulio/orca-one pull request #7
Opened 2024-03-26 05:08 UTC by WandersonAlves

Hey, hello!

This PR tries to centralize the way the application handles colors. 

For `Screen` classes, the main idea is to use `Launcher.cpp` as the starter point for applying the color scheme. The code will grab the colors from the configuration and set then before `ScreenManager` gets called.

For other components like `ButtonMenu`, `ProgressBar` and `ScrollBar`, we simply get the colors from configuration and use them for configuring the components.

`SplashScreen` lives he own thing, after drawing the orca image, we clean the screen using the default values.

After discussing the PR, we can use this to update the documentation for dev usage, teaching how to create new `Screen`s, add new items on `MainMenuScreen`, etc.

🚀

2024-03-27 22:41 UTC, marivaaldo commented on src/applications/launcher/Launcher.cpp
> +    auto backgroundColor = device->getSettings()->getBackgroundColor();
Please change to:

```
auto primaryColor = settings->getPrimaryColor();
auto backgroundColor = settings->getBackgroundColor();
```

2024-03-27 22:49 UTC, marivaaldo commented on src/applications/launcher/Launcher.cpp
> +    auto backgroundColor = device->getSettings()->getBackgroundColor();
Please change to:

```cpp
auto primaryColor = settings->getPrimaryColor();
auto backgroundColor = settings->getBackgroundColor();
```

2024-03-27 22:50 UTC, marivaaldo commented on src/applications/services/gui/ProgressBar.cpp
> +    this->_width = displayInterface->getSettings().width - (progressBarMargin * 2);
Please change to:

```cpp
this->_width = displaySettings.width - (progressBarMargin * 2);
```

2024-03-27 22:51 UTC, marivaaldo requested changes
Please see comments. Thank you so much!

2024-03-28 01:40 UTC, WandersonAlves commented
Hey @marivaaldo, the issues found are fixed, please take a look again

2024-03-28 11:11 UTC, marivaaldo approved these changes

2024-03-28 11:15 UTC, merged