Feature/read nfc uid
cyberjulio/orca-one pull request #8
Opened 2024-03-27 20:14 UTC by HugoOliveiraSoares

Hello!

This pull request implements a new feature that allows reading information from an NFC tag using the PN532 module as a reader.
With this feature it is possible to read: 
- UID
- ATQ
- SAK

Uses Seeed-Studio's [PN532](https://github.com/Seeed-Studio/PN532) libraries and [NDEF](https://github.com/don/NDEF) by Don Coleman that were added to the lib directory

2024-03-28 14:27 UTC, marivaaldo requested changes
Please see comments. Thank you so much!

2024-03-28 14:27 UTC, marivaaldo commented on src/applications/nfc/ReadTag/ReadTagRun.h
Please rename to `ReadTagRunScreen.h`

2024-03-28 14:27 UTC, marivaaldo commented on src/applications/nfc/ReadTag/ReadTagRun.cpp
Please rename to `ReadTagRunScreen.cpp`

2024-03-28 14:27 UTC, marivaaldo commented on src/domain/entities/DeviceBase.cpp
Please add `i2cInterface` to `begin` method.

2024-03-28 14:27 UTC, marivaaldo commented on src/domain/entities/I2CInterfaceBase.h
You can use `I2CInterfaceBase` (using `DSDA_PIN` and `DSCL_PIN`) like `SDCardInterfaceBase` to not needs implement I2CInterface on each device.

2024-03-28 14:27 UTC, marivaaldo commented on platformio.ini
I'ts possible to install libs `NDEF, PN532, etc` in this file?

2024-03-29 12:11 UTC, HugoOliveiraSoares commented
Hi @marivaaldo, the problems found have been fixed. Thanks for the review.

2024-03-30 23:48 UTC, marivaaldo requested changes
Please, you can rebase with `develop` and change PR to merge into `develop` branch? Sorry to not comment this previously and thanks for you great job!

2024-03-31 11:20 UTC, HugoOliveiraSoares commented
> Please, you can rebase with `develop` and change PR to merge into `develop` branch? Sorry to not comment this previously and thanks for you great job!

Sure, I will rebase the branch with `develop`

2024-03-31 14:32 UTC, marivaaldo approved these changes

2024-04-01 14:30 UTC, merged